SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `hnsdesktop` (
  `user_id` int(10) unsigned NOT NULL,
  `notepad` mediumtext NOT NULL,
  `theme_id` int(2) NOT NULL DEFAULT '1',
  `bg_color` varchar(20) NOT NULL,
  `wallpaper_file` varchar(50) NOT NULL,
  `wallpaper_position` varchar(20) NOT NULL,
  `wallpaper_repeat` varchar(20) NOT NULL,
  `font_color` varchar(20) NOT NULL,
  `transparency` int(1) NOT NULL DEFAULT '1',
  `screensaver` int(1) NOT NULL DEFAULT '1',
  `screensaver_time` int(3) NOT NULL,
  `yt_playlist` text NOT NULL,
  `music_song` varchar(255) NOT NULL,
  `browser_home` varchar(100) NOT NULL,
  `browser_favorites` varchar(255) NOT NULL,
  `browser_history` varchar(255) NOT NULL,
  `players` varchar(255) NOT NULL,
  `twttr_playlist` text NOT NULL,
  `launcher_autorun` varchar(255) NOT NULL,
  `launcher_thumbs` varchar(255) NOT NULL,
  `launcher_startmenuapps` varchar(255) NOT NULL,
  `launcher_startmenutools` varchar(255) NOT NULL,
  `launcher_quickstart` varchar(255) NOT NULL,
  `launcher_tray` varchar(255) NOT NULL,
  `app_documents` varchar(100) NOT NULL,
  `app_preferences` varchar(100) NOT NULL,
  `app_notepad` varchar(100) NOT NULL,
  `app_flash_name` varchar(100) NOT NULL,
  `app_ytinstant` varchar(100) NOT NULL,
  `app_piano` varchar(100) NOT NULL,
  `app_about_hnsdesktop` varchar(100) NOT NULL,
  `app_feedback` varchar(100) NOT NULL,
  `app_tic_tac_toe` varchar(100) NOT NULL,
  `app_friends` varchar(100) NOT NULL,
  `app_goom_radio` varchar(100) NOT NULL,
  `app_search` varchar(100) NOT NULL,
  `app_chat` varchar(100) NOT NULL,
  `app_music` varchar(100) NOT NULL,
  `app_web_browser` varchar(100) NOT NULL,
  `app_app_explorer` varchar(100) NOT NULL,
  `app_calculator` varchar(100) NOT NULL,
  `app_twitter` varchar(100) NOT NULL,
  UNIQUE KEY `uid` (`user_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;